
services:
  app:
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      LOG_LEVEL: debug
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: db_wedding
      DB_USERNAME: db_wedding
      DB_PASSWORD: R3DY@D3M3TR10
      DB_ROOT_PASSWORD: D3LG4D0#S3QU3IR0S
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  frontend:
    build:
      context: ../boda-frontend
      dockerfile: Dockerfile.dev
    container_name: boda_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ../boda-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api
      - VITE_USE_FAKE=false
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - app
    networks:
      - web

  mysql:
    environment:
      MYSQL_PASSWORD: R3DY@D3M3TR10
      MYSQL_ROOT_PASSWORD: D3LG4D0#S3QU3IR0S
    networks:
      - web

networks:
  web:
    driver: bridge
